probabilities  = "./probabilities/probs-plural-1.toml"
sharer_trust   = "./sharer_trust/trust.toml"
prospect       = "./prospect/x[4-8_33]-ym3.csv"
cpt            = "./cpt/cpt.csv"
initial_states = "./initial_states/initial_states.toml"
condition      = "./condition/risk2.toml"
uncertainty    = "./uncertainty/uncertainty.toml"
